version: "3.9"

services:
  nginx:
    image: nginx:1.25
    container_name: nginx
    restart: unless-stopped
    depends_on:
      - express-app-admin-1
      - express-app-admin-2
      - express-app-admin-3
    ports:
      - "80:80"
      # - "443:443"   # enable when certs ready
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - letsencrypt:/etc/letsencrypt
      - certbot_www:/var/www/certbot
      - nginx_cache:/var/cache/nginx
    networks:
      - app-net

  express-app-admin-1:
    image: "__DOCKER_HUB_IMAGE__"
    container_name: express-app-admin-1
    restart: unless-stopped
    environment:
      NODE_ENV: "production"
      PORT: "5000"
    expose:
      - "5000"
    networks:
      - app-net
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://127.0.0.1:5000/health || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 10
      start_period: 10s

  express-app-admin-2:
    image: "__DOCKER_HUB_IMAGE__"
    container_name: express-app-admin-2
    restart: unless-stopped
    environment:
      NODE_ENV: "production"
      PORT: "5000"
    expose:
      - "5000"
    networks:
      - app-net
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://127.0.0.1:5000/health || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 10
      start_period: 10s

  express-app-admin-3:
    image: "__DOCKER_HUB_IMAGE__"
    container_name: express-app-admin-3
    restart: unless-stopped
    environment:
      NODE_ENV: "production"
      PORT: "5000"
    expose:
      - "5000"
    networks:
      - app-net
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://127.0.0.1:5000/health || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 10
      start_period: 10s

  certbot:
    image: certbot/certbot:latest
    entrypoint: sh
    command: -c "trap : TERM INT; sleep infinity"
    volumes:
      - letsencrypt:/etc/letsencrypt
      - certbot_www:/var/www/certbot
    networks:
      - app-net

networks:
  app-net:
    driver: bridge

volumes:
  letsencrypt:
  certbot_www:
  nginx_cache:





