version: "3.8"

services:
  nginx:
    image: "nginx:1.25"
    container_name: nginx
    init: true
    restart: unless-stopped
    depends_on:
      - express-app-admin-1
      - express-app-admin-2
      - express-app-admin-3
    ports:
      - "80:80"   # HTTP only
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - nginx_cache:/var/cache/nginx
    healthcheck:
      test: ["CMD-SHELL", "nginx -t -q || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 10s
    stop_grace_period: 10s
    networks: [app-net]

  express-app-admin-1:
    image: "nitheesh2005/admin-app:latest"
    container_name: express-app-admin-1
    init: true
    restart: unless-stopped
    environment:
      NODE_ENV: "production"
      PORT: "5000"
    expose:
      - "5000"
    healthcheck:
      test: ["CMD-SHELL", "curl -fs http://localhost:5000/health || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 20
      start_period: 40s
    stop_grace_period: 10s
    networks: [app-net]

  express-app-admin-2:
    image: "nitheesh2005/admin-app:latest"
    container_name: express-app-admin-2
    init: true
    restart: unless-stopped
    environment:
      NODE_ENV: "production"
      PORT: "5000"
    expose:
      - "5000"
    healthcheck:
      test: ["CMD-SHELL", "curl -fs http://localhost:5000/health || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 20
      start_period: 40s
    stop_grace_period: 10s
    networks: [app-net]

  express-app-admin-3:
    image: "nitheesh2005/admin-app:latest"
    container_name: express-app-admin-3
    init: true
    restart: unless-stopped
    environment:
      NODE_ENV: "production"
      PORT: "5000"
    expose:
      - "5000"
    healthcheck:
      test: ["CMD-SHELL", "curl -fs http://localhost:5000/health || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 20
      start_period: 40s
    stop_grace_period: 10s
    networks: [app-net]

networks:
  app-net:
    driver: bridge

volumes:
  nginx_cache:


