version: "3.9"

services:
  nginx:
    image: "nginx:1.25"
    container_name: nginx
    restart: unless-stopped
    depends_on:
      - express-app-admin-1
      - express-app-admin-2
      - express-app-admin-3
    ports:
      - "80:80"
      # - "443:443"   # enable when certs ready
    volumes:
      - type: bind
        source: ./nginx/conf.d
        target: /etc/nginx/conf.d
        read_only: true
      - type: bind
        source: ./nginx/nginx.conf
        target: /etc/nginx/nginx.conf
        read_only: true
      - type: volume
        source: letsencrypt
        target: /etc/letsencrypt
      - type: volume
        source: certbot_www
        target: /var/www/certbot
      - type: volume
        source: nginx_cache
        target: /var/cache/nginx
    networks:
      - app-net

  express-app-admin-1:
    image: "niteesh2005/admin-app:latest"
    container_name: express-app-admin-1
    restart: unless-stopped
    environment:
      NODE_ENV: "production"
      PORT: "5000"
    expose:
      - "5000"
    networks:
      - app-net
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://127.0.0.1:5000/health || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 10
      start_period: 10s

  express-app-admin-2:
    image: "niteesh2005/admin-app:latest"
    container_name: express-app-admin-2
    restart: unless-stopped
    environment:
      NODE_ENV: "production"
      PORT: "5000"
    expose:
      - "5000"
    networks:
      - app-net
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://127.0.0.1:5000/health || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 10
      start_period: 10s

  express-app-admin-3:
    image: "niteesh2005/admin-app:latest"
    container_name: express-app-admin-3
    restart: unless-stopped
    environment:
      NODE_ENV: "production"
      PORT: "5000"
    expose:
      - "5000"
    networks:
      - app-net
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://127.0.0.1:5000/health || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 10
      start_period: 10s

  certbot:
    image: "certbot/certbot:latest"
    entrypoint: "sh"
    command: ["-c", "trap : TERM INT; sleep infinity"]
    volumes:
      - type: volume
        source: letsencrypt
        target: /etc/letsencrypt
      - type: volume
        source: certbot_www
        target: /var/www/certbot
    networks:
      - app-net

networks:
  app-net:
    driver: bridge

volumes:
  letsencrypt: {}
  certbot_www: {}
  nginx_cache: {}




