name: Docker CD

on:
  workflow_run:
    workflows: ["Docker CI"]
    types: [completed]

concurrency:
  group: docker-cd-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy to Server
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (infra files)
        uses: actions/checkout@v4

      - name: Debug: show infra layout
        run: |
          echo "PWD=$(pwd)"
          ls -lah
          echo "---- infra ----"
          ls -lah infra || true
          echo "---- infra/nginx ----"
          ls -lah infra/nginx || true
          echo "---- infra/nginx/conf.d ----"
          ls -lah infra/nginx/conf.d || true
          echo "---- infra/scripts ----"
          ls -lah infra/scripts || true

      - name: Guard: ensure infra exists
        run: |
          test -d infra || (echo "::error::infra/ not found at repo root" && exit 1)
          test -f infra/docker-compose.yml || (echo "::error::infra/docker-compose.yml missing" && exit 1)

      # copy to VPS; flatten "infra/" so files land directly in /opt/app
      - name: Copy infra to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          overwrite: true
          debug: true
          source: "infra/docker-compose.yml,infra/nginx/**,infra/scripts/**"
          target: "/opt/app/"
          strip_components: 1

      - name: Deploy via SSH (docker compose + 3 replicas + optional TLS)
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          debug: true
          script_stop: true
          script: |
            set -Eeuo pipefail
            echo "Starting deployment…"
            cd /opt/app

            # sanity check
            [ -f docker-compose.yml ] || (echo "::error::docker-compose.yml missing in /opt/app" && exit 1)
            [ -f nginx/nginx.conf ] || (echo "::error::nginx/nginx.conf missing" && exit 1)
            [ -f nginx/conf.d/app.conf ] || (echo "::error::nginx/conf.d/app.conf missing" && exit 1)

            docker --version
            docker compose version

            # Docker Hub login (only if repo is private)
            if [ -n "${{ secrets.DOCKER_HUB_ACCESS_TOKEN || '' }}" ]; then
              echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" | docker login \
                -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin
            fi

            # replace image placeholder in compose
            sed -i "s|__DOCKER_HUB_IMAGE__|${{ secrets.DOCKER_HUB_USERNAME }}/admin-app:latest|g" docker-compose.yml

            # stamp domain into nginx vhost (for HTTPS). LE will NOT work for raw IPs.
            if [ -n "${{ secrets.DOMAIN || '' }}" ]; then
              sed -i "s/DOMAIN_PLACEHOLDER/${{ secrets.DOMAIN }}/g" nginx/conf.d/app.conf || true
              sed -i "s/www.DOMAIN_PLACEHOLDER/www.${{ secrets.DOMAIN }}/g" nginx/conf.d/app.conf || true
            fi

            # pull latest images referenced by compose
            docker compose pull || true

            # start nginx + one app first (so ACME http-01 can work)
            docker compose up -d nginx express-app-admin-1

            # generate initial upstreams if script exists; otherwise static upstreams in app.conf are used
            if [ -f scripts/render_upstream.sh ]; then
              chmod +x scripts/render_upstream.sh
              bash scripts/render_upstream.sh || true
            fi

            # first-run: issue Let's Encrypt certs if DOMAIN provided
            if [ -n "${{ secrets.DOMAIN || '' }}" ]; then
              # check inside nginx container rather than guessing volume names
              if ! docker compose exec -T nginx sh -c "test -f /etc/letsencrypt/live/${{ secrets.DOMAIN }}/fullchain.pem"; then
                echo "Issuing TLS cert for ${{ secrets.DOMAIN }}…"
                docker compose run --rm certbot certbot certonly \
                  --webroot -w /var/www/certbot \
                  -d "${{ secrets.DOMAIN }}" -d "www.${{ secrets.DOMAIN }}" \
                  --email "${{ secrets.LETSENCRYPT_EMAIL }}" --agree-tos --no-eff-email || true
                docker compose restart nginx || true
              fi
            fi

            # bring up all three replicas
            docker compose up -d express-app-admin-1 express-app-admin-2 express-app-admin-3

            # regenerate upstreams with all replicas and reload nginx
            if [ -f scripts/render_upstream.sh ]; then
              bash scripts/render_upstream.sh || docker compose exec -T nginx nginx -s reload || true
            else
              docker compose exec -T nginx nginx -s reload || true
            fi

            echo "Deployment complete ✅"
