name: Docker CD

on:
  workflow_run:
    workflows: ["Docker CI"]
    types: [completed]
  workflow_dispatch: {}   # allow manual runs for testing

concurrency:
  group: "docker-cd-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy to Server
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate required secrets
        env:
          VPS_HOST: ${{ secrets.VPS_HOST }}
          VPS_USERNAME: ${{ secrets.VPS_USERNAME }}
          VPS_SSH_KEY: ${{ secrets.VPS_SSH_KEY }}
          DKR_USER: ${{ secrets.DOCKER_HUB_USERNAME }}
          DKR_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        run: |
          set -Eeuo pipefail
          set -x
          [ -n "$VPS_HOST" ] || { echo "::error::Missing VPS_HOST"; exit 1; }
          [ -n "$VPS_USERNAME" ] || { echo "::error::Missing VPS_USERNAME"; exit 1; }
          [ -n "$VPS_SSH_KEY" ] || { echo "::error::Missing VPS_SSH_KEY"; exit 1; }
          if [ -z "$DKR_USER" ] || [ -z "$DKR_TOKEN" ]; then
            echo "::warning::Docker Hub credentials not set. Using public images."
          fi
          echo "Secrets validated ✅"

      - name: Pack infra as tarball
        run: |
          set -Eeuo pipefail
          set -x
          tar -czf infra.tar.gz -C infra .
          ls -lah infra.tar.gz

      - name: SSH connectivity check
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          script_stop: true
          debug: true
          script: |
            set -Eeuo pipefail
            set -x
            echo "SSH OK on $(hostname)"
            whoami
            uname -a

      - name: Prepare /opt/app on VPS
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          script_stop: true
          debug: true
          script: |
            set -Eeuo pipefail
            set -x
            sudo rm -rf /opt/app/* || true
            sudo mkdir -p /opt/app
            sudo chown -R "$USER:$USER" /opt/app
            ls -lah /opt/app || true

      - name: Copy tarball to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          overwrite: true
          debug: true
          source: infra.tar.gz
          target: /opt/app/

      - name: Unpack infra on VPS
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          script_stop: true
          debug: true
          script: |
            set -Eeuo pipefail
            set -x
            cd /opt/app
            tar -xzf infra.tar.gz
            rm -f infra.tar.gz
            echo "Remote /opt/app layout:"
            ls -lah /opt/app
            echo "Nginx files:"
            ls -lah /opt/app/nginx /opt/app/nginx/conf.d

      - name: Deploy via SSH (HTTP only)
        uses: appleboy/ssh-action@v0.1.7
        env:
          DKR_USER: ${{ secrets.DOCKER_HUB_USERNAME }}
          DKR_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          debug: true
          script_stop: true
          script: |
            set -Eeuo pipefail
            set -x

            APP_DIR="/opt/app"
            cd "$APP_DIR"

            # Sanity checks
            [ -f docker-compose.yml ] || { echo "::error::docker-compose.yml missing"; exit 1; }
            [ -f nginx/nginx.conf ] || { echo "::error::nginx/nginx.conf missing"; exit 1; }
            [ -f nginx/conf.d/app.conf ] || { echo "::error::nginx/conf.d/app.conf missing"; exit 1; }

            # Ensure Docker + Compose
            if ! command -v docker >/dev/null 2>&1; then
              echo "Installing Docker..."
              curl -fsSL https://get.docker.com | sh
              sudo usermod -aG docker "$USER" || true
            fi
            sudo systemctl enable --now docker || true
            sudo docker --version
            sudo docker compose version || true

            # Docker Hub login (if private)
            if [ -n "${DKR_USER:-}" ] && [ -n "${DKR_TOKEN:-}" ]; then
              echo "$DKR_TOKEN" | sudo docker login -u "$DKR_USER" --password-stdin
            fi

            # Replace placeholder image if exists
            if grep -q "__DOCKER_HUB_IMAGE__" docker-compose.yml; then
              if [ -n "${DKR_USER:-}" ]; then
                sudo sed -i "s|__DOCKER_HUB_IMAGE__|$DKR_USER/admin-app:latest|g" docker-compose.yml
              else
                echo "::warning::__DOCKER_HUB_IMAGE__ found but DOCKER_HUB_USERNAME is empty"
              fi
            fi

            # Validate docker-compose before start
            sudo docker compose -f docker-compose.yml config

            # 🔹 FULL CLEANUP to avoid duplicate upstreams
            sudo docker compose down --remove-orphans
            sudo docker system prune -af
            sudo rm -f nginx/conf.d/upstreams.generated.conf || true

            # Start nginx + first app
            sudo docker compose up -d nginx express-app-admin-1

            # Validate nginx config
            sudo docker compose run --rm nginx nginx -t

            # Render upstreams safely
            if [ -f scripts/render_upstream.sh ]; then
              sudo chmod +x scripts/render_upstream.sh
              sudo bash scripts/render_upstream.sh
            fi

            # Start remaining replicas
            sudo docker compose up -d express-app-admin-2 express-app-admin-3

            # Reload nginx safely
            sudo docker compose exec -T nginx nginx -s reload

            # Health check
            curl -fsS -m 5 http://127.0.0.1/health || echo "::warning::/health not responding"

            echo "Deployment complete ✅ (HTTP only)"

