name: Docker CI

on:
  push:
    branches: [ master, main ]
    tags: ["*"]   # also run on tags if you want
  pull_request:
    branches: [ master, main ]
  workflow_dispatch: {}

concurrency:
  group: docker-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Only login on non-PR events
      - name: Log in to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push (./server/Dockerfile)
        uses: docker/build-push-action@v6
        with:
          context: ./server
          file: ./server/Dockerfile
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/admin-app:latest
            ${{ secrets.DOCKER_HUB_USERNAME }}/admin-app:${{ github.sha }}

      # Optional: Remove old `latest` before re-pushing
      - name: Remove old latest tag from Docker Hub
        if: github.event_name != 'pull_request'
        run: |
          curl -X DELETE \
            -u "${{ secrets.DOCKER_HUB_USERNAME }}:${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" \
            "https://hub.docker.com/v2/repositories/${{ secrets.DOCKER_HUB_USERNAME }}/admin-app/tags/latest/"


