name: Docker CI

on:
  push:
    branches: [ master, main ]
  workflow_dispatch: {}

concurrency:
  group: docker-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Login to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # Remove all previous tags/images for admin-app
      - name: Remove all previous tags from Docker Hub
        run: |
          echo "Fetching all tags..."
          tags=$(curl -s -u "${{ secrets.DOCKER_HUB_USERNAME }}:${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" \
            "https://hub.docker.com/v2/repositories/${{ secrets.DOCKER_HUB_USERNAME }}/admin-app/tags/?page_size=100" \
            | jq -r '.results[].name')
          
          echo "Deleting old tags..."
          for tag in $tags; do
            echo "Deleting $tag..."
            curl -s -X DELETE \
              -u "${{ secrets.DOCKER_HUB_USERNAME }}:${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" \
              "https://hub.docker.com/v2/repositories/${{ secrets.DOCKER_HUB_USERNAME }}/admin-app/tags/$tag/"
          done

      # Build and push only latest
      - name: Build and push latest
        uses: docker/build-push-action@v6
        with:
          context: ./server
          file: ./server/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/admin-app:latest
