name: Docker CD

on:
  workflow_run:
    workflows: ["Docker CI"]
    types:
      - completed

jobs:
  deploy:
    name: Deploy to Server
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          debug: true
          script_stop: true
          script: |
            set -Eeuo pipefail
            echo "Starting deployment process..."

            # (Optional) Login to Docker Hub if your repo is private
            # echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login \
            #   -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

            # Pull the latest Docker image
            docker pull "${{ secrets.DOCKER_HUB_USERNAME }}/admin-app:latest"
            echo "Pulled the latest Docker image."

            # Stop and remove the existing container if it exists
            docker stop admin-app || true
            docker rm admin-app || true

            # Run the new container
            docker run -d --name admin-app \
              -p 5000:5000 \
              --restart unless-stopped \
              "${{ secrets.DOCKER_HUB_USERNAME }}/admin-app:latest"

            echo "Deployed the new Docker container."
