
name: Docker CD

on:
  workflow_run:
    workflows: ["Docker CI"]
    types: [completed]
  workflow_dispatch: {}   # allow manual runs for testing

concurrency:
  group: "docker-cd-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy to Server
    # Run when CI succeeded OR when manually triggered
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout (infra files)
        uses: actions/checkout@v4

      - name: Validate required secrets
        env:
          REQ_VPS_HOST: ${{ secrets.VPS_HOST }}
          REQ_VPS_USERNAME: ${{ secrets.VPS_USERNAME }}
          REQ_VPS_SSH_KEY: ${{ secrets.VPS_SSH_KEY }}
          DKR_USER: ${{ secrets.DOCKER_HUB_USERNAME }}
          DKR_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        run: |
          set -Eeuo pipefail
          set -x
          [ -n "$REQ_VPS_HOST" ] || { echo "::error::Missing VPS_HOST"; exit 1; }
          [ -n "$REQ_VPS_USERNAME" ] || { echo "::error::Missing VPS_USERNAME"; exit 1; }
          [ -n "$REQ_VPS_SSH_KEY" ] || { echo "::error::Missing VPS_SSH_KEY"; exit 1; }
          if [ -z "$DKR_USER" ] || [ -z "$DKR_TOKEN" ]; then
            echo "::warning::Docker Hub creds not set. Assuming public image."
          fi
          echo "Secrets OK ✅"

      # - name: Guard: ensure infra exists in repo
      #   run: |
      #     set -Eeuo pipefail
      #     set -x
      #     test -d infra || { echo "::error::infra/ not found at repo root"; exit 1; }
      #     test -f infra/docker-compose.yml || { echo "::error::infra/docker-compose.yml missing"; exit 1; }
      #     test -f infra/nginx/nginx.conf || { echo "::error::infra/nginx/nginx.conf missing"; exit 1; }
      #     test -d infra/nginx/conf.d || { echo "::error::infra/nginx/conf.d missing"; exit 1; }

      - name: Pack infra as tarball
        run: |
          set -Eeuo pipefail
          set -x
          tar -czf infra.tar.gz -C infra .
          ls -lah infra.tar.gz

      - name: SSH Hello (connectivity check)
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          script_stop: true
          debug: true
          script: |
            set -Eeuo pipefail
            set -x
            echo "SSH OK on $(hostname)"
            whoami
            uname -a

      - name: Prep /opt/app on VPS
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          script_stop: true
          debug: true
          script: |
            set -Eeuo pipefail
            set -x
            sudo mkdir -p /opt/app
            sudo chown -R "$USER:$USER" /opt/app
            ls -lah /opt/app || true

      - name: Copy tarball to VPS (scp)
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          overwrite: true
          debug: true
          source: infra.tar.gz
          target: /opt/app/

      - name: Unpack infra on VPS
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          script_stop: true
          debug: true
          script: |
            set -Eeuo pipefail
            set -x
            cd /opt/app
            tar -xzf infra.tar.gz
            rm -f infra.tar.gz
            echo "Remote /opt/app layout:"
            ls -lah /opt/app
            echo "Nginx files:"
            ls -lah /opt/app/nginx /opt/app/nginx/conf.d

      - name: Deploy via SSH (HTTP only)
        uses: appleboy/ssh-action@v0.1.7
        env:
          DKR_USER: ${{ secrets.DOCKER_HUB_USERNAME }}
          DKR_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          debug: true
          script_stop: true
          script: |
            set -Eeuo pipefail
            set -x

            APP_DIR="/opt/app"
            cd "$APP_DIR"

            # Sanity checks
            [ -f docker-compose.yml ] || { echo "::error::docker-compose.yml missing"; exit 1; }
            [ -f nginx/nginx.conf ] || { echo "::error::nginx/nginx.conf missing"; exit 1; }
            [ -f nginx/conf.d/app.conf ] || { echo "::error::nginx/conf.d/app.conf missing"; exit 1; }

            # Ensure Docker + Compose
            if ! command -v docker >/dev/null 2>&1; then
              echo "Installing Docker..."
              curl -fsSL https://get.docker.com | sh
              sudo usermod -aG docker "$USER" || true
            fi
            sudo systemctl enable --now docker || true
            sudo docker --version
            sudo docker compose version || true

            # Docker Hub login (only if private image)
            if [ -n "${DKR_USER:-}" ] && [ -n "${DKR_TOKEN:-}" ]; then
              echo "$DKR_TOKEN" | sudo docker login -u "$DKR_USER" --password-stdin
            fi

            # Replace image placeholder if present
            if grep -q "__DOCKER_HUB_IMAGE__" docker-compose.yml; then
              if [ -n "${DKR_USER:-}" ]; then
                sudo sed -i "s|__DOCKER_HUB_IMAGE__|$DKR_USER/admin-app:latest|g" docker-compose.yml
              else
                echo "::warning::__DOCKER_HUB_IMAGE__ found but DOCKER_HUB_USERNAME is empty"
              fi
            fi

            # Validate compose BEFORE starting
            sudo docker compose -f docker-compose.yml config

            # Start nginx + one app first (lets nginx come up quickly)
            sudo docker compose up -d nginx express-app-admin-1

            # Validate Nginx config inside the container
            sudo docker compose exec -T nginx nginx -t

            # Optional upstream rendering script (if present)
            if [ -f scripts/render_upstream.sh ]; then
              sudo chmod +x scripts/render_upstream.sh
              sudo bash scripts/render_upstream.sh || true
            fi

            # Start remaining replicas
            sudo docker compose up -d express-app-admin-2 express-app-admin-3

            # Reload Nginx
            sudo docker compose exec -T nginx nginx -s reload || true

            # Health probe (adjust path if your app doesn't expose /health)
            curl -fsS -m 5 http://127.0.0.1/health || echo "::warning::/health not responding (ensure route exists)"

            echo "Deployment complete ✅ (HTTP only)"
