name: Docker CD

on:
  workflow_run:
    workflows: ["Docker CI"]
    types: [completed]

concurrency:
  group: docker-cd-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy to Server
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout (infra files)
        uses: actions/checkout@v4

      - name: Debug: show infra layout
        run: |
          set -Eeuo pipefail
          set -x
          echo "PWD=$(pwd)"
          ls -lah
          echo "---- infra ----"
          ls -lah infra || true
          echo "---- infra/nginx ----"
          ls -lah infra/nginx || true
          echo "---- infra/nginx/conf.d ----"
          ls -lah infra/nginx/conf.d || true
          echo "---- infra/scripts ----"
          ls -lah infra/scripts || true

      - name: Guard: ensure infra exists
        run: |
          set -Eeuo pipefail
          set -x
          test -d infra || (echo "::error::infra/ not found at repo root" && exit 1)
          test -f infra/docker-compose.yml || (echo "::error::infra/docker-compose.yml missing" && exit 1)

      - name: Smoke test SSH + remote dir
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          script_stop: true
          debug: true
          script: |
            set -Eeuo pipefail
            set -x
            whoami
            uname -a
            sudo mkdir -p /opt/app
            sudo chown -R $USER:$USER /opt/app
            ls -lah /opt/app || true

      # Copy to VPS; flatten "infra/" so files land directly in /opt/app
      - name: Copy infra to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          overwrite: true
          debug: true
          source: "infra/docker-compose.yml,infra/nginx/**,infra/scripts/**"
          target: "/opt/app/"
          strip_components: 1

      - name: Deploy via SSH (docker compose + 3 replicas + optional TLS)
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          debug: true
          script_stop: true
          script: |
            set -Eeuo pipefail
            set -x

            cd /opt/app

            # Sanity checks
            [ -f docker-compose.yml ] || (echo "::error::docker-compose.yml missing in /opt/app" && exit 1)
            [ -f nginx/nginx.conf ] || (echo "::error::nginx/nginx.conf missing" && exit 1)
            [ -f nginx/conf.d/app.conf ] || (echo "::error::nginx/conf.d/app.conf missing" && exit 1)

            # Ensure Docker + Compose
            if ! command -v docker >/dev/null 2>&1; then
              echo "Installing Docker..."
              curl -fsSL https://get.docker.com | sh
              sudo usermod -aG docker $USER || true
            fi
            sudo systemctl enable --now docker || true
            sudo docker --version
            sudo docker compose version || true

            # Docker Hub login (only if private)
            if [ -n "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" ]; then
              echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" | sudo docker login \
                -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin
            fi

            # Replace image placeholder in compose
            if grep -q "__DOCKER_HUB_IMAGE__" docker-compose.yml; then
              sudo sed -i "s|__DOCKER_HUB_IMAGE__|${{ secrets.DOCKER_HUB_USERNAME }}/admin-app:latest|g" docker-compose.yml
            fi

            # Inject domain into nginx vhost (HTTPS only works with a real domain)
            if [ -n "${{ secrets.DOMAIN }}" ]; then
              sudo sed -i "s/DOMAIN_PLACEHOLDER/${{ secrets.DOMAIN }}/g" nginx/conf.d/app.conf || true
              sudo sed -i "s/www.DOMAIN_PLACEHOLDER/www.${{ secrets.DOMAIN }}/g" nginx/conf.d/app.conf || true
            fi

            # Pull latest images referenced by compose (non-fatal if first run)
            sudo docker compose pull || true

            # Start nginx + one app first (for ACME http-01 if we use TLS)
            sudo docker compose up -d nginx express-app-admin-1

            # Optional: generate upstreams
            if [ -f scripts/render_upstream.sh ]; then
              sudo chmod +x scripts/render_upstream.sh
              sudo bash scripts/render_upstream.sh || true
            fi

            # First-run certs (skipped if DOMAIN unset). Let's Encrypt won't issue for raw IPs.
            if [ -n "${{ secrets.DOMAIN }}" ]; then
              if ! sudo docker compose exec -T nginx sh -c "test -f /etc/letsencrypt/live/${{ secrets.DOMAIN }}/fullchain.pem"; then
                echo "Issuing TLS cert for ${{ secrets.DOMAIN }}…"
                sudo docker compose run --rm certbot certbot certonly \
                  --webroot -w /var/www/certbot \
                  -d "${{ secrets.DOMAIN }}" -d "www.${{ secrets.DOMAIN }}" \
                  --email "${{ secrets.LETSENCRYPT_EMAIL }}" --agree-tos --no-eff-email || true
                sudo docker compose restart nginx || true
              fi
            fi

            # Bring up all replicas
            sudo docker compose up -d express-app-admin-1 express-app-admin-2 express-app-admin-3

            # Reload nginx after upstream updates
            if [ -f scripts/render_upstream.sh ]; then
              sudo bash scripts/render_upstream.sh || sudo docker compose exec -T nginx nginx -s reload || true
            else
              sudo docker compose exec -T nginx nginx -s reload || true
            fi

            echo "Deployment complete ✅"
